src/views/tables/ReactBootstrapTable.js

- 제목 : feat( #13 ): 테이블 기본 폼
<br/>
-  테이블 기본 폼 
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-17] 테이블

---

package.json
src/store/apps/login/userSlice.js
src/views/auth/LoginFormik.js
src/views/auth/RegisterFormik.js
src/views/sample-pages/Profile.js

#10 
아이디
휴대폰번호
이메일
중복확인 백엔드 서버쪽에서 함
중복시 login 으로 navigate X

[2024-07-17] 회원가입 구현

---

src/layouts/header/Header.js
src/layouts/header/ProfileDD.js
src/layouts/sidebars/vertical/Sidebar.js
src/store/apps/login/userSlice.js
src/views/sample-pages/Profile.js

#11 
내정보 수정하기 기능 추가
수정하고 redux state 에 바뀐 정보 넣음
헤더 사이드바에 이름 연동

[2024-07-17] 회원 수정하기 기능 추가

---

src/views/sample-pages/Profile.js

[2024-07-17] 비밀번호 변경

---

src/layouts/FullLayout.js
src/layouts/header/Header.js
src/views/auth/LoginFormik.js

[2024-07-18] 로그인 기억하기 기능 추가

---

src/layouts/FullLayout.js
src/layouts/sidebars/sidebardata/SidebarData.js
src/routes/Router.js
src/views/airportStore/airportStore.js
src/views/auth/LoginFormik.js

[2024-07-18] 점포 조회

---

src/routes/Router.js
src/store/apps/airplane/gateSlice.js
src/views/airplane/Gate.js
src/views/airplane/gateDetail.js

- 제목 : feat(): 탑승구
<br/>
- 탑승구 row 클릭
<br/>
<br/>
- [# ](이슈 주소)
<br/>

[2024-07-18] 탑승구 row

---

.idea/material_theme_project_new.xml
.idea/misc.xml
.idea/vcs.xml
.idea/workspace.xml
src/store/apps/inspection/inspetctionSlice.js
src/views/inspection/inspection.js

- 제목 : feat(issue 번호): 안전 점검 수정 중
(확인 후 지워주세요)
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-18] 안전 점검 수정 중

---

src/store/Store.js
src/store/apps/airplane/gateSlice.js
src/views/airplane/Gate.js
src/views/airplane/gateDetail.js

- 제목 : feat(28): 탑승구 조회
<br/>
- 탑승구 전체 조회
- 탑승구 상세 조회
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #28 ]
<br/>

[2024-07-18] 탑승구 조회

---

.env
package-lock.json
package.json
src/firebase.js
src/layouts/header/Header.js
src/layouts/header/HorizontalHeader.js
src/layouts/header/ProfileDD.js
src/layouts/sidebars/vertical/Sidebar.js
src/routes/Router.js
src/store/apps/login/userSlice.js
src/views/auth/Profile.js
src/views/auth/imgUpload.js

- 제목 : feat(#34 ):
<br/>
- firebase 이미지 업로드 기능 이용해 이미지 생성
<br/>
<br/>
- 업로드 폼 추가

[2024-07-19] 프로필 이미지 업로드

---

src/views/airplane/gateDetail.js

- 제목 : feat(28): 탑승구 상세 조회
<br/>
- 탑승구 상세 조
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #28](이슈 주소)
<br/>

[2024-07-19] 탑승구 상세 조회

---

src/store/apps/airplane/gateSlice.js
src/views/airplane/gateDetail.js

- 제목 : feat(39): 탑승구 수정 기능
<br/>
- 탑승구 수정 기능
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #39]
<br/>

[2024-07-19] 탑승구 수정 기능

---

src/layouts/sidebars/sidebardata/HorizontalSidebarData.js
src/layouts/sidebars/sidebardata/SidebarData.js
src/routes/Router.js
src/store/apps/airplane/gateSlice.js
src/views/airplane/Gate.js
src/views/airplane/gateDetail.js

- 제목 : feat(42): 탑승구 삭제
<br/>
- 탑승구 soft delete 상태값 변경
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #42]
<br/>

[2024-07-19] 탑승구 삭제

---

src/views/airportStore/airportStoreDBUpdate.js
src/views/airportStore/airportStoreDetail.js
src/views/auth/imgUpload.js

- 제목 :  시설물 CRUD
<br/>
- 시설물 CRUD 하기
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-19] 시설물 CRUD

---

.gitignore
src/store/apps/airplane/gateSlice.js
src/views/auth/Profile.js
src/views/auth/ProfileUploader.css
src/views/auth/imgUpload.js

- 제목 :프로필 수정하기 이미지 추가
<br/>
- 컴포넌트 css 맞게 불러옴
<br/>
<br/>
<br/>

[2024-07-19] 프로필 수정하기 이미지 추가

---

src/routes/Router.js
src/store/apps/inspection/inspectionSlice.js
src/views/inspection/inspection.js
src/views/inspection/inspectionDetail.js
src/views/inspection/inspectionUpdate.js

- 제목 : feat(47): inspection 안전 점검 전체 조회 연결
<br/>
- inspection 안전 점검 전체 조회 연결
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #47]
<br/>

[2024-07-19] 안전 점검 전체 조회

---

src/routes/Router.js
src/store/Store.js
src/store/apps/airplane/chkinCounterSlice.js
src/views/airplane/CheckinCounter.js
src/views/airplane/CheckinCounterDetail.js

- 제목 : feat(issue 48): 체크인 카운터 기능
<br/>
- 체크인 카운터 전체 조회
- 체크인 카운터 상세 조회
- 체크인 카운터 정보 수정
- 체크인 카운터 soft delete
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #48 #49 # 50]
<br/>

[2024-07-21] 체크인 카운터 기능

---

src/routes/Router.js
src/store/Store.js
src/store/apps/airplane/baggageClaimSlice.js
src/store/apps/airplane/chkinCounterSlice.js
src/views/airplane/BaggageClaim.js
src/views/airplane/CheckinCounterDetail.js
src/views/airplane/Gate.js
src/views/airplane/ReactBootstrapTable.scss
src/views/airplane/gateDetail.js

- 제목 : feat(52): 수화물 수취대 전체 조회
<br/>
- 수화물 수취대 전체  조회
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #52]
<br/>

[2024-07-21] 수화물 수취대  전체 조회

---

src/routes/Router.js
src/views/airplane/BaggageClaim.js
src/views/airplane/BaggageClaimsDetail.js

- 제목 : feat(52,53,54): 수화물 수취대 기능
<br/>
- 수화물 수취대 상세 조회
- 수화물 수취대 정보 수정
- 수화물 수취대 soft delete
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #52 #53 #54 ]
<br/>

[2024-07-21] 수화물 수취대 기능

---

src/routes/Router.js
src/views/auth/Profile.js
src/views/auth/image/CanvasUtils.js
src/views/auth/image/ImgDialog.js
src/views/auth/image/UploadImage.js
src/views/auth/image/styles.js
src/views/auth/imgUpload.js

(확인 후 지워주세요)
<br/>
- react-easy-crop 라이브러리 적용
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-21] 프로필 사진 crop

---

src/layouts/sidebars/sidebardata/HorizontalSidebarData.js
src/layouts/sidebars/sidebardata/SidebarData.js
src/routes/Router.js
src/store/Store.js
src/store/apps/airplane/airplaneSlice.js
src/views/airplane/Airplane.js
src/views/airplane/BaggageClaim.js
src/views/airplane/CheckinCounter.js
src/views/airplane/Gate.js

- 제목 : feat(58): 비행기 전체 조
<br/>
- 비행기 전체 조회
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #58]
<br/>

[2024-07-21] 비행기 전체 조회

---

src/routes/Router.js
src/views/airplane/AirplaneDetail.js

- 제목 : feat(58,60,61): 비행기 상세조회 수정/삭
<br/>
- 비행기 상세 조회
- 비행기 정보 수정
- 비행기 soft delete
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #58 #60 #61]
<br/>

[2024-07-21] 비행기 수정/삭제

---

package-lock.json
package.json
src/layouts/sidebars/sidebardata/HorizontalSidebarData.js
src/layouts/sidebars/sidebardata/SidebarData.js
src/routes/Router.js
src/store/apps/maintenance/maintenanceSlice.js
src/views/maintenance/maintenance.js
src/views/maintenance/maintenanceDetails.js

- 제목 : feat(64): 정비 상세 조회
<br/>
- 정비 상세조회 리엑트 연결
<br/>
<br/>
- 정비 수정한 내용이 저장이 안 되어서 코드 수정을 해야 할 것 같음
<br/>
- [frontend #64 ](이슈 주소)
<br/>

[2024-07-22] 정비 상세 조회

---

src/store/apps/maintenance/maintenanceSlice.js
src/views/maintenance/maintenanceDetails.js

- 제목 : feat(65):정비 수정
<br/>
- 정비 수정 
<br/>
<br/>
- 승인을 해야한다~
<br/>
- [backend #65 ](이슈 주소)
<br/>

[2024-07-22] 정비 수정 리엑트 연결

---

src/routes/Router.js
src/store/apps/maintenance/maintenanceSlice.js
src/views/maintenance/maintenance.js
src/views/maintenance/maintenanceRegist.js

- 제목 : feat(67): 정비 등록
<br/>
- 정비 전체 조회 페이지에서 등록 버튼 생성
- 등록 버튼 클릭 시, 정비 등록하는 상세 페이지로 이동
<br/>
<br/>
<br/>
- [frontend #67 ](이슈 주소)
<br/>

[2024-17-23] 정비 등록 리엑트 연결

---

src/views/maintenance/maintenance.js

- 제목 : feat(33): 정비 전체 조회 수정
<br/>
- 전체 조회에 structure 값 들어오게 수정
<br/>
- [frontend #33 ](이슈 주소)
<br/>

[2024-07-23] 정비 전체 조회 수정

---

src/store/apps/inspection/inspectionSlice.js
src/views/inspection/inspectionDetail.js

- 제목 : feat(issue 번호): 안전 점검 수정 삭제
<br/>
- 안전 점검 수정 삭제
<br/>
<br/>
- 요
<br/>
<br/>

[2024-07-23]안전 점검 수정 삭제

---

src/views/inspection/inspection.js
src/views/inspection/inspectionDetail.js

- 제목 : feat(issue 번호): 안전 점검 등록 수정 삭제 최종
<br/>
- 안전 점검 등록 수정 삭제 최종
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-23]안전 점검 등록 수정 삭제 최종

---

.idea/dataSources.xml
.idea/workspace.xml
src/layouts/sidebars/sidebardata/HorizontalSidebarData.js
src/layouts/sidebars/sidebardata/SidebarData.js
src/routes/Router.js
src/views/facilities/facilities.js
src/views/facilities/facilitiesDetail.js

- 제목 #80 
<br/>
편의시설 조회 상세조회 수정 삭제 연결
<br/>
<br/>
등록 기능 추가
<br/>
#80 
<br/>

편의시설 조회 상세조회 수정 삭제 연결

---

package.json
src/views/airplane/gateDetail.js
src/views/airportStore/airportStore.js
src/views/auth/AuthCode.js

- 제목 : feat(#83 ): 신규회원 인증코드 보내기 폼 추가
- 
<br/>
- 신규회원 인증코드 생성, 휴대폰, 이메일 번호 보내기 폼 추가
<br/>
<br/>
- 아이디 찾기/ 비밀번호 찾기 추가
<br/>
<br/>

[2024-07-23] 신규회원 인증코드 보내기 폼 추가

---

.idea/workspace.xml
src/views/auth/RegisterFormik.js
src/views/inspection/inspection.js

- 제목 : feat(issue 번호): 안전 점검 등록 수정 삭제 최최종
<br/>
- 안전 점검 등록 수정 삭제 최최종
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-23]안전 점검 등록 수정 삭제 최최종

---

src/views/airplane/BaggageClaim.js
src/views/airplane/CheckinCounter.js

<br/>
- 체크인 카운터 지도 popover 기능
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-23] 체크인카운터 지도

---

.idea/workspace.xml
package.json
src/views/airportStore/airportStore.js
src/views/auth/Profile.js

[2024-07-22] 점포 테이블 삭제 추가

---

src/layouts/sidebars/sidebardata/SidebarData.js
src/routes/Router.js
src/views/airplane/CheckinCounter.js
src/views/airplane/CheckinCounterRegist.js
src/views/airplane/img.css

- 제목 : feat(89): 체크인 카운터 지도
<br/>
- 체크인 카운터 지도 사용/미사용 표시
- 체크인 카운터 지도 사용중이면 정보 / 미사용중이면 등록
- 등록 누르면 등록 페이지로 이동
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #89 ]
<br/>

[2024-07-23] 체크인 카운터 지도

---

src/routes/Router.js
src/views/airplane/BaggageClaim.js
src/views/airplane/BaggageClaimRegist.js
src/views/airplane/CheckinCounter.js
src/views/airplane/img.css

- 제목 : feat(91): 수화물 수취대 지도
<br/>
-  수화물 수취대 지도 사용/미사용 표시
- 수화물 수취대 지도 사용중이면 정보나오고 상세보기 / 미사용중이면 등록
- 등록 누르면 등록 페이지로 이동
- 상세보기 나오면 그 수화물 수취대 상세보기
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #91 ]
<br/>

[2024-07-23]수화물 수취대 지도

---

src/views/airplane/BaggageClaimRegist.js
src/views/airplane/CheckinCounterRegist.js

- 제목 : feat(97,98): 체크인 카운터/수화물 수취대 등록 데이터
<br/>
- 체크인 카운터 등록 작성 시 비행기 정보 끌고오기
- 수화물 수취대 등록 작성 시 비행기 정보 끌고오기
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #97 #98](이슈 주소)
<br/>

[2024-07-24] 체크인 카운터/ 수화물 수취대 등록

---

src/components/apps/userContacts/UserDetail.js
src/layouts/sidebars/sidebardata/SidebarData.js
src/routes/Router.js
src/views/chat/LiveChatting.js
src/views/chat/TestChatting.js
vite.config.js

- 제목 : feat(#101 ):  채팅 커밋
<br/>
채팅 기능 추가
<br/>
<br/>

[2024-07-24] 채팅기능

---

src/routes/Router.js

<br/>
- router 경로 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-25] router

---

src/views/airplane/BaggageClaimRegist.js
src/views/airplane/CheckinCounterRegist.js

- 제목 : feat(97,98): 체크인카운터/수화물 수취대 비행기 정보
<br/>
- 비행기 정보 중복 제거
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #97 #98](이슈 주소)
<br/>

[2024-07-25] 체크인카운터/수화물 수취대 비행기 정보

---

package-lock.json
src/layouts/sidebars/sidebardata/HorizontalSidebarData.js
src/layouts/sidebars/sidebardata/SidebarData.js
src/routes/Router.js
src/store/Store.js
src/store/apps/equipment/equipmentSlice.js
src/views/equipment/equipment.js
src/views/equipment/equipmentDetail.js
src/views/equipment/equipmentUpdate.js
src/views/inspection/inspection.js
src/views/inspection/inspectionDetail.js

- 제목 : feat(issue 번호): equipment_quantity 전체조회
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- equipment_quantity 상세 조회
<br/>

[2024.07.25]equipment_quantity 전체조회

---

package.json
src/components/apps/managerDargAndDrop/ManagerDragAndDrop.js
src/routes/Router.js
src/views/airportStore/airportStoreDetail.js

- 제목 : feat(#151):  담당자 등록 삭제 수정 드래그앤드롭 추가
<br/>
- 변경 할 때 서버에 저장되도록 수정
<br/>
<br/>
<br/>

[2024-07-24] 담당자 등록 삭제 수정 드래그앤드롭 추가

---

src/views/storage/Storage.js
src/views/storage/StorageDetail.js

- 제목 : feat(104): storage 수정, 삭제
<br/>
- storage 수정, 삭제
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #104 ](이슈 주소)
<br/>

[2024-07-25] storage 수정, 삭제

---

package-lock.json
src/store/apps/equipment/equipmentSlice.js
src/views/equipment/equipmentDetail.js
src/views/equipment/equipmentUpdate.js

- 제목 : #115 [2024.07-26] equipment 상세조회
<br/>
- equipment 상세조회
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024.07-26] equipment 상세조회

---

package.json
src/components/apps/audioPlayer/Player.js
src/layouts/header/Header.js

[2024-07-26] 음악

---

src/views/airplane/BaggageClaimRegist.js
src/views/airplane/CheckinCounter.js
src/views/airplane/CheckinCounterDetail.js
src/views/airplane/CheckinCounterRegist.js

- 제목 : feat(issue 번호): 체크인 카운터 오류 수정
<br/>
- 체크인 카운터 오류 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-26] 체크인 카운터 오류 수정

---

src/store/apps/airplane/api.js
src/store/apps/airplane/baggageClaimSlice.js
src/store/apps/airplane/chkinCounterSlice.js
src/views/airplane/BaggageClaimRegist.js
src/views/airplane/CheckinCounterRegist.js

- 제목 : feat(97,98): 체크인카운터/ 수화물 수취대 등록
<br/>
- 체크인카운터 backend와 연결
- 수화물 수취대 backend와 연결
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #97 #98](이슈 주소)
<br/>

[2024-07-28] 체크인카운터/ 수화물 수취대 등록

---

src/routes/Router.js
src/store/apps/airplane/gateSlice.js
src/views/airplane/Gate.js
src/views/airplane/GateRegist.js

- 제목 : feat(122): 기능명
<br/>
- 탑승구 등록 폼
<br/>
<br/>
- 등록 backend 와 연결
<br/>
- [frontend #122 ](이슈 주소)
<br/>

[2024-07-28] 탑승구 등록 폼

---

src/routes/Router.js
src/views/airplane/GateRegist.js

- 제목 : feat(124): 라우터 수정
<br/>
- 라우터 경로 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #124 ](이슈 주소)
<br/>

[2024-07-29] 라우터 수정

---

src/views/airplane/BaggageClaimsDetail.js
src/views/airplane/CheckinCounterDetail.js
src/views/airplane/gateDetail.js

- 제목 : feat(127): 비행기 컬럼 수정
<br/>
- 비행기 수정 할 때 컬럼 수정 안되는것 눈에 보이게 색을 변경
- 체크인 카운터 수정
- 탑승구 수정
- 수화물 수취대 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #127](이슈 주소)
<br/>

[2024-07-29] 비행기 컬럼 수정

---

src/routes/Router.js
src/store/apps/storage/storageSlice.js
src/views/storage/Storage.js
src/views/storage/StorageDetail.js
src/views/storage/StorageRegist.js

- 제목 : feat(130): 창고 등록
<br/>
- 창고 등록
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #130 ](이슈 주소)
<br/>

[2024.07.29] storage 등록

---

src/routes/Router.js
src/store/apps/equipment/equipmentSlice.js
src/store/apps/inspection/inspectionSlice.js
src/views/equipment/equipment.js
src/views/equipment/equipmentDetail.js
src/views/equipment/equipmentUpdate.js
src/views/inspection/inspection.js
src/views/inspection/inspectionDetail.js
src/views/inspection/inspectionUpdate.js

- 제목 : #132  기능명
<br/>
- [2024.07-29] inspection 등록, 장비재고 등록 빼고 기능 완성
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024.07-29] inspection 등록, 장비재고 등록 빼고 기능 완성

---

package.json
src/components/apps/chat/ChatElements.js
src/components/apps/chat/ChatElements.scss
src/components/apps/userContacts/UserDetail.js
src/layouts/FullLayout.js
src/store/Store.js
src/store/apps/websocket/WebSocketMiddleware.js
src/store/apps/websocket/WebSocketSlice.js
src/views/chat/LiveChatting.js
src/views/chat/TestChatting.js

- 제목 : 채팅 기능 추가
<br/>
- 실시간 채팅 기능 추가
- 
<br/>
- 대시보드에서 채팅 알림 추가
<br/>
<br/>

[2024-07-29] 채팅 기능 추가

---

package-lock.json
src/views/inspection/inspectionDetail.js
src/views/inspection/inspectionRegist.js

- 제목 : #132 안전 점검 등록
<br/>
- 안전 점검 등록
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024.07.30]안전 점검 등록

---

src/routes/Router.js
src/store/apps/equipment/equipmentSlice.js
src/store/apps/inspection/inspectionSlice.js
src/views/equipment/equipment.js
src/views/equipment/equipmentRegist.js
src/views/inspection/inspectionDetail.js

- 제목 #139 장비재고 등록
<br/>
- 장비재고 등록
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024.07.30] 장비재고 등록

---

src/views/dashboards/AirQuality.js
src/views/dashboards/Dashboard1.js

- 제목 : feat(134): 대시보드 미세먼지 차트 추가
<br/>
- 대시보드에 터미널별 미세먼지 차트
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #134](이슈 주소)
<br/>

[2024-07-30] 대시보드 미세먼지 차트 추가

---

src/routes/Router.js
src/store/apps/facilities/facilitiesSlice.js
src/views/facilities/facilities.js
src/views/facilities/facilitiesRegist.js

(확인 후 지워주세요)
<br/>
- 편의시설 등록
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024.07.31] 편의시설 등록

---

src/views/facilities/facilities.js

- 제목 : feat(148): 편의시설 등록 버튼 수정
<br/>
- 편의시설 등록 버튼 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #148 ](이슈 주소)
<br/>

[2024.07.31] 편의시설 등록 버튼 수정

---

src/routes/Router.js
src/store/apps/maintenance/maintenanceSlice.js
src/views/airplane/img.css
src/views/maintenance/maintenance.js
src/views/maintenance/maintenanceDetails.js
src/views/maintenance/maintenanceRegist.js

- 제목 : feat(153): 정비 등록
<br/>
- 정비 시설물 조인
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #153](이슈 주소)
<br/>

[2024-08-01] 정비 시설물 조인

---

src/components/apps/approve/ContactDetails.js
src/components/apps/approve/ContactFilter.js
src/components/apps/approve/ContactList.js
src/components/apps/approve/ContactListItem.js
src/store/apps/approve/ContactSlice.js

- 제목 : feat(151): 승인 데이터 불러와서 조회
<br/>
- 전체 조회에는 매니저이름과 상태 여부 끌고왔음
- 상세조회에서는 각각의 시설물의 맞게 정보들이 조회
<br/>
<br/>
- 승인처리 하고
- 뷰페이지 깔끔하게
<br/>
- [frontend #151](이슈 주소)
<br/>

[2024-08-01] 승인 데이터 불러와서 조회

---

src/components/apps/chat/ChatElements.js
src/components/location/Location.js
src/views/airportStore/airportStore.js
src/views/airportStore/airportStoreDetail.js
src/views/chat/LiveChatting.js
src/views/facilities/facilitiesDetail.js

- 제목 :  위치 엘리먼트 추가
<br/>
- 위치 파일 추가함. 각자 추가 후 DB 저장 예정
- 
<br/>

[2024-08-01] 위치 엘리먼트 추가

---

src/views/airportStore/airportStore.js

[2024-08-01] 점포 픽스

---

src/components/apps/approve/ContactDetails.js
src/components/apps/approve/ContactList.css

- 제목 : feat(156): 승인 처리 가능
<br/>
- 각각의 시설물들이 등록을 하게 되면 승인페이지로 넘어와
- 승인페이지에서 승인버튼을 클릭하게 되면
- 시설물 등록이 됩니다~
<br/>
<br/>
- 승인 페이지 이쁘게 만들기~(이지은 맘에 들게)
<br/>
- [frontend #156 ](이슈 주소)
<br/>

[2024-08-02] 승인 처리 가능

---

src/store/apps/maintenance/maintenanceSlice.js
src/views/maintenance/EquipmentStock.js
src/views/maintenance/maintenanceDetails.js
src/views/maintenance/maintenanceRegist.js

- 제목 : feat(162): 정비 장비 등록
<br/>
- 정비완료시 장비 등록
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #162 ](이슈 주소)
<br/>

[2024-08-02] 정비 장비 등록

---

src/layouts/sidebars/sidebardata/HorizontalSidebarData.js
src/layouts/sidebars/sidebardata/SidebarData.js
src/store/apps/maintenance/maintenanceSlice.js
src/views/maintenance/EquipmentStock.js
src/views/maintenance/maintenanceDetails.js

- 제목 : feat(162): 기능명
<br/>
- 정비에서 장비 등록시 비용 계산
- 장비 등록시 수정/장비 재고 버튼 불가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #162](이슈 주소)
<br/>

[2024-08-02] 정비에서 장비 등록시 비용 추가 / 버튼 막기

---

src/routes/Router.js
src/views/auth/Error500.js

- 제목 : feat(160): 500 오류 페이지
<br/>
- 500 오류 페이지 만들기
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #160 ](이슈 주소)
<br/>

[2024.08.02] 500 오류 페이지

---

src/components/apps/liveStatus/StatusProfileImg.js
src/components/apps/managerDargAndDrop/ManagerDragAndDrop.js
src/components/location/Location.js
src/layouts/header/Header.js
src/layouts/sidebars/vertical/Sidebar.js
src/views/airplane/BaggageClaimsDetail.js
src/views/airplane/Gate.js
src/views/equipment/equipmentDetail.js
src/views/equipment/equipmentRegist.js
src/views/facilities/facilitiesDetail.js
src/views/storage/StorageDetail.js

- 제목 : 탑승구 위치 담당자 등록 수정
<br/>
- 탑승구 위치 담당자 등록 수정
<br/>

[2024-08-03] 탑승구 위치 담당자 등록 수정

---

src/views/airplane/BaggageClaimsDetail.js
src/views/airplane/CheckinCounterDetail.js
src/views/airportStore/airportStoreDetail.js

- 제목 :체크인 카운터 담당자/ 위치 추가
<br/>
- 체크인 카운터 담당자 추가
- 체크인 카운터 위치 추가

[2024-08-03] 체크인 카운터 담당자/ 위치 추가

---

src/components/apps/Equipment/EcoSidebar.js
src/components/apps/Equipment/EquipmentListing.js
src/routes/Router.js
src/views/equipment/equipmentDetail.js
src/views/equipment/equipmentRegist.js

- 제목 : feat(176): 기능명
<br/>
- 장비 이름 중복 불가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #176](이슈 주소)
<br/>

[2024-08-06]장비 이름 중복 불가

---

src/components/apps/qrCode/middleContent/CreateQRList.js

- 제목 : feat(issue 번호):sudo ufw enable
<br/>
- 안전 점검 최종 완성
- 적어주세요
<br/>
<br/>

[2024-08-06] 컬럼 수정

---

src/components/apps/approve/ContactSerch.js
src/components/apps/qrCode/middleContent/CreateQRList.js
src/store/apps/createQR/CreateQRSlice.js

- 제목 : feat(#171): Qr 발급 검색기능 추가
<br/>
-  검색기능 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-07] Qr 발급 검색기능 추가

---

src/store/apps/inspection/inspectionSlice.js
src/views/dashboards/Datachart.js

- 제목 : #183 안전점검 대쉬보드
<br/>
- 안전점검 대쉬보드
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-07] 대쉬보드 안전점검 차트

---

src/views/dashboards/Dashboard1.js
src/views/dashboards/EquimentCharts.js

- 제목 #188 : 장비재고 대쉬보드
<br/>
- 장비재고 대쉬보드
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-07] 장비재고 대쉬보드

---

src/layouts/header/Header.js
src/layouts/header/NotificationDD.js
src/store/apps/equipment/equipmentSlice.js

- 제목 : feat(190): 승인알림
<br/>
- 승인 처리가 안된 요청들 알림
<br/>
<br/>
- 관리자/직원 알림 나누기
- 직원/ 승인 완료된 알림 
<br/>
- [frontend #190](이슈 주소)
<br/>

[2024-08-08]승인 알림

---

src/views/airplane/Gate.js
src/views/airplane/Gate2.js
src/views/dashboards/Dashboard1.js

- 제목 : #196 
<br/>
- 탑승구 사용여부 이미지표시
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
-#196 
<br/>

[2024-08-08]탑승구 사용여부 이미지표시

---

src/views/airplane/Gate.js

(확인 후 지워주세요)
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-08] hotfix

---

src/views/airplane/Airplane.js
src/views/airplane/BaggageClaim.js
src/views/airplane/Gate.js
src/views/airplane/Gate2.js

[2024-08-08] useEffect 생명주기 문제

---

src/layouts/header/NotificationDD.js
src/layouts/sidebars/sidebardata/HorizontalSidebarData.js
src/layouts/sidebars/sidebardata/SidebarData.js
src/routes/Router.js
src/views/calendar/CalendarApp.js
src/views/calendar/calendar.scss
src/views/dashboards/Dashboard1.js

- 제목 : feat(202): 캘린더 추가
<br/>
- 정비 일정 기능 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #202 ](이슈 주소)
<br/>

[2024-08-09]캘린더 추가

---

src/components/apps/daumpost/DaumPost.js
src/components/apps/daumpost/DaumPost.module.css
src/layouts/sidebars/sidebardata/SidebarData.js
src/views/auth/Profile.js
src/views/auth/findPassword.js
src/views/storage/StorageRegist.js

- 제목 : 다음 주소 찾기 기능 추가
<br/>
- 주소 수정 부분 다음 post 컴포넌트 추가
<br/>
<br/>

[2024-08-09] 주소 찾기 기능 추가

---

src/layouts/FullLayout.js
src/store/apps/login/userSlice.js
src/views/airplane/Airplane.js
src/views/airplane/BaggageClaim.js
src/views/airplane/CheckinCounter.js
src/views/airplane/Gate.js
src/views/airplane/gateDetail.js
src/views/airportStore/airportStore.js
src/views/inspection/inspection.js

- 제목 : 권한 설정 추가 / 안전 점검 페이지 수정
<br/>
- 권한 설정 추가 / 안전 점검 페이지 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-09] 권한 설정 추가 / 안전 점검 페이지 수정

---

src/store/apps/websocket/WebSocketSlice.js
src/views/airplane/BaggageClaim.js
src/views/airplane/Gate2.js
src/views/airplane/Gate3.js
src/views/airplane/Gate4.js
src/views/airplane/Gate5.js

- 제목 :게이트 모달 정보 넣기 추가
<br/>
- 게이트 모달 정보 넣기 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-10] 게이트 모달 정보 넣기 추가

---

src/components/apps/chat/ChatElements.js
src/layouts/FullLayout.js
src/store/apps/websocket/WebSocketSlice.js
src/views/airplane/BaggageClaim.js

- 제목 : 라이브 채팅 토스트
<br/>
- 라이브 채팅 토스트
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-10] 라이브 채팅 토스트

---

src/views/airplane/CheckinCounter.js

- 제목 : #215 
<br/>
- 체크인 카운터 DB값 표시
<br/>
<br/>
- 디테일잡기 
<br/>
#215 
<br/>

[2024-08-10] 체크인 카운터 DB값 표시

---

src/layouts/header/MegaDD.css
src/layouts/header/MegaDD.js
src/layouts/sidebars/sidebardata/SidebarData.js
src/routes/Router.js
src/views/aiquestion/AiQuestion.js
src/views/dashboards/Dashboard1.js
src/views/inspection/inspectionDetail.js
vite.config.js

- 제목 :  AI 질문하기 기능 추가
<br/>
-  AI 질문하기 기능 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-11] AI 질문하기 기능 추가

---

package.json
src/layouts/FullLayout.js
src/store/apps/websocket/WebSocketSlice.js
src/views/aiquestion/AiQuestion.js
src/views/inspection/inspectionDetail.js

- 제목 : ai 질문하기 공항 기능 추가
<br/>
- ai 질문하기 공항 기능 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-11] ai 질문하기 공항 기능 추가

---

src/layouts/logo/AuthLogo.js

- 제목 : feat(issue 번호): [2024-08-11] 로고 변경
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-11] 로고 변경

---

src/views/airplane/AirplaneDetail.js
src/views/airplane/BaggageClaimsDetail.js
src/views/airplane/CheckinCounterDetail.js
src/views/airplane/Gate.js
src/views/airplane/gateDetail.js
src/views/airportStore/airportStoreDetail.js
src/views/equipment/equipmentDetail.js
src/views/facilities/facilitiesDetail.js
src/views/inspection/inspectionDetail.js
src/views/maintenance/maintenanceDetails.js
src/views/storage/StorageDetail.js

- 제목 : 삭제버튼 관리자만 보이게 수정
<br/>
- 삭제버튼 관리자만 보이게 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-11] 삭제버튼 관리자만 보이게 수정

---

src/views/auth/LoginFormik.js

- 제목 : #225 
<br/>
- 로그인 페이지 한글 수정
<br/>
<br/>
- 
<br/>
#225 
<br/>

[2024-08-11] 로그인 페이지 한글 수정

---

src/views/airplane/gateDetail.js
src/views/auth/Profile.js

[2024-08-12] hotfix

---

src/components/apps/approve/ContactDetails.js
src/views/CustomModal.js
src/views/airplane/AirplaneDetail.js
src/views/airplane/BaggageClaim.js
src/views/airplane/BaggageClaimRegist.js
src/views/airplane/BaggageClaimsDetail.js
src/views/airplane/CheckinCounterDetail.js
src/views/airplane/CheckinCounterRegist.js
src/views/airplane/GateRegist.js
src/views/airplane/gateDetail.js
src/views/airportStore/airportStoreDetail.js
src/views/dashboards/Dashboard1.js
src/views/dashboards/MaintenanceChart.js
src/views/dashboards/Map.js
src/views/dashboards/TaskList.js
src/views/dashboards/TaskList.scss
src/views/equipment/equipmentDetail.js
src/views/equipment/equipmentRegist.js
src/views/facilities/facilitiesDetail.js
src/views/facilities/facilitiesRegist.js
src/views/inspection/inspectionDetail.js
src/views/inspection/inspectionRegist.js
src/views/maintenance/EquipmentStock.js
src/views/maintenance/maintenanceDetails.js
src/views/maintenance/maintenanceRegist.js
src/views/storage/StorageDetail.js
src/views/storage/StorageRegist.js

- 제목 : feat(issue 번호): alert창 모달로 변경
<br/>
- alert창 모달로 변경
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [frontend #228](이슈 주소)
<br/>

[2024-08-11]alert창 모달로 변경

---

src/views/airplane/BaggageClaimsDetail.js
src/views/airplane/CheckinCounterDetail.js
src/views/airplane/Gate.js
src/views/airplane/gateDetail.js

<br/>
- 비행기 수정 승인 null
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-11] 비행기 수정 승인 null

---

src/views/airplane/Gate2.js
src/views/airplane/gateDetail.js

- 제목 : #231 
<br/>
- 탑승구 디테일 수정
<br/>
<br/>
- 발표준비 잘하자!
<br/>
<br/>

[2024-08-12]탑승구 디테일 수정

---

src/components/location/Location.js
src/views/airplane/AirplaneDetail.js
src/views/airplane/gateDetail.js
src/views/equipment/equipmentDetail.js
src/views/equipment/equipmentRegist.js
src/views/facilities/facilitiesDetail.js
src/views/facilities/facilitiesRegist.js

- 제목 :위치 수정
<br/>
- 위치 컬럼 수정
- 위치 인풋 태그 수정
- 장비 위치 창고로만 있게 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-12] 시설물 위치 수정

---

src/views/airplane/Airplane.js
src/views/airplane/BaggageClaim.js
src/views/airplane/CheckinCounter.js
src/views/airplane/Gate.js

- 제목 : f비행기 전체조회 삭제, 추가 기능 제거
<br/>
- 비행기 전체조회 삭제, 추가 기능 제거
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-12] 비행기 전체조회 삭제, 추가 기능 제거

---

src/components/apps/approve/ContactList.js
src/components/apps/approve/ContactListItem.js
src/store/apps/airplane/baggageClaimSlice.js
src/views/airplane/AirplaneDetail.js
src/views/airplane/BaggageClaimRegist.js
src/views/airplane/BaggageClaimsDetail.js
src/views/airplane/CheckinCounterDetail.js
src/views/airplane/CheckinCounterRegist.js
src/views/airplane/GateRegist.js
src/views/airplane/gateDetail.js
src/views/airportStore/airportStoreDetail.js
src/views/facilities/facilitiesDetail.js
src/views/facilities/facilitiesRegist.js
src/views/storage/StorageDetail.js
src/views/storage/StorageRegist.js

- 제목 : feat(issue 번호): 승인 요청자 추가
<br/>
- 승인 요청자 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-11]승인 요청자 추가

---

src/views/equipment/equipmentRegist.js

- 제목 : feat(issue 번호): 장비 등록 수정
<br/>
- 장비 등록 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-12]장비 등록 수정

---

src/store/apps/storage/storageSlice.js
src/views/airplane/CheckinCounterDetail.js
src/views/airplane/gate2.css
src/views/storage/StorageRegist.js

- 제목 : #238 
<br/>
- 창고 체크인 카운터 디테일 수정
<br/>
<br/>
- 발표준비
<br/>
#238 
<br/>

[2024-08-12]창고 체크인 카운터 디테일 수정

---

src/components/apps/approve/ContactDetails.js

- 제목 : feat(issue 206): 승인 페이지 테이블 처리
<br/>
- 승인 페이지 테이블 처리
<br/>
<br/>
<br/>
- [frontend #206 ](이슈 주소)
<br/>

[2024-08-12] 승인 페이지 테이블 처리

---

src/views/equipment/equipmentRegist.js
src/views/facilities/facilitiesDetail.js
src/views/facilities/facilitiesRegist.js

- 제목 : feat(issue 번호): 편의시설 승인 오류 수정
<br/>
- 편의시설 승인 오류 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-12]편의시설 승인 오류 수정

---

src/views/airplane/CheckinCounterDetail.js

(확인 후 지워주세요)
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-12]수화물 수취대 디테일 수정

---

src/views/airplane/Airplane.js
src/views/airplane/AirplaneDetail.js

- 제목 : #245 
<br/>
- 비행기 API 정보 ,디테일 수정
<br/>
<br/>
- 발표준비
<br/>
#245 
<br/>

[2024-08-12]비행기 API 정보 ,디테일 수정

---

src/components/apps/approve/ContactDetails.js
src/views/facilities/facilitiesDetail.js
src/views/facilities/facilitiesRegist.js
src/views/storage/StorageRegist.js

- 제목 : feat(issue 번호): 승인 오류 수정
<br/>
- 승인 오류 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-12]승인 오류 수정

---

src/components/apps/approve/ContactList.js
src/components/apps/approve/ContactListItem.js
src/components/apps/qrCode/rightContent/CreateQRDetails.js
src/views/storage/StorageDetail.js

- 제목 :  승인 오류 수정
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-12] 승인 오류 수정

---

src/views/airportStore/airportStore.js
src/views/facilities/facilities.js

- 제목 : #252 
<br/>
- 편의시설 점포 버튼 수정
<br/>
<br/>
- 발표준비
<br/>
#252 
<br/>

[2024-08-13] 편의시설 점포 수정

---

src/views/airplane/gateDetail.js
src/views/storage/Storage.js

[2024-08-13] hotfix

---

src/components/apps/Equipment/EquipmentListing.js
src/components/apps/approve/ContactDetails.js
src/components/apps/approve/ContactList.js
src/components/apps/chat/ChatElements.js
src/components/apps/qrCode/rightContent/CreateQRDetails.js
src/components/location/Location.js
src/layouts/breadcrumbs/BreadCrumbs.js
src/layouts/sidebars/sidebardata/SidebarData.js
src/store/apps/airplane/baggageClaimSlice.js
src/store/apps/facilities/facilitiesSlice.js
src/store/apps/storage/storageSlice.js
src/views/airplane/Airplane.js
src/views/airplane/BaggageClaim.js
src/views/airplane/BaggageClaimRegist.js
src/views/airplane/Gate.js
src/views/airplane/gateDetail.js
src/views/airportStore/airportStore.js
src/views/auth/AuthCode.js
src/views/auth/RegisterFormik.js
src/views/facilities/facilitiesRegist.js
src/views/storage/StorageDetail.js
src/views/storage/StorageRegist.js

- 제목 : feat(issue 번호): 콘솔로그
<br/>
- 콘솔로그 지우기
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13]콘솔로그

---

src/views/maintenance/maintenanceDetails.js

- 제목 : feat(issue 번호): 정비 상세조회 오류
<br/>
- 정비 상세조회 오류
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 정비 상세조회 오류

---

src/views/facilities/facilitiesDetail.js

- 제목 : feat(issue 번호): 편의시설 승인 오류
<br/>
- 편의시설 승인 오류
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 편의시설 승인 오류

---

src/views/airplane/BaggageClaimsDetail.js
src/views/airplane/CheckinCounterDetail.js

- 제목 :  #259 
<br/>
- 수화물 수취대 , 체크인 카운터 위치정보 수정
<br/>
<br/>
- 끝내주게 집가기
<br/>
#259 
<br/>

[2024-08-13] 수화물 수취대 , 체크인 카운터 위치정보 수정

---

src/components/apps/approve/ContactList.js
src/views/storage/StorageRegist.js

- 제목 : feat(issue 번호): 승인 오류
<br/>
- 승인 오류
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 승인 오류

---

src/views/airplane/CheckinCounter.js

- 제목 : #262 
<br/>
- 체크인 카운터 도착지 정보 추가
<br/>
<br/>
-끝내주게 숨쉬기
<br/>
#262 
<br/>

[2024-08-13] 체크인 카운터 도착지 정보 추가

---

src/components/apps/approve/ContactList.js

- 제목 : [2024-08-13] 승인 수정
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 승인 수정

---

src/components/apps/approve/ContactDetails.js
src/views/calendar/CalendarApp.js
src/views/facilities/facilitiesRegist.js
src/views/maintenance/maintenanceRegist.js

- 제목 : feat(issue 번호): 캘린더 오류 수정
<br/>
- 캘린더 오류 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 캘린더 오류 수정

---

src/views/airplane/CheckinCounterDetail.js
src/views/facilities/facilitiesDetail.js
src/views/facilities/facilitiesRegist.js

- 제목 : feat(issue 번호): 편의시설 수정
<br/>
- 편의시설 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 편의시설 수정

---

src/layouts/header/Header.js

- 제목 : f[2024-08-13] 헤더 알림 수정
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 헤더 알림 수정

---

src/views/airplane/BaggageClaim.js
src/views/inspection/inspection.js
src/views/maintenance/maintenance.js

- 제목 : #268 
<br/>
- 정비 시설물 이름 변경
<br/>
<br/>
-  끝내주게 쉴준비
<br/>
#268 
<br/>

[2024-08-13] 정비 시설물 이름 변경

---

src/views/airplane/CheckinCounter.js

- 제목 : 
<br/>
- 체크인 카운터 상태표시 수정
<br/>
<br/>
- 체크인 카운터 상태표시 수정
<br/>
<br/>

[2024-08-13] 체크인 카운터 상태표시 수정

---

src/views/maintenance/maintenanceDetails.js

- 제목 : 담당자 추가
<br/>
- 기담당자 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 담당자 추가

---

src/layouts/header/Header.js
src/layouts/header/NotificationDD.js

- 제목 : feat(issue 번호): 알림 수정
<br/>
- 알림 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 알림 수정

---

src/views/inspection/inspection.js

(확인 후 지워주세요)
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 정비 조회 데이터 테이블 옮기기

---

src/store/apps/websocket/WebSocketSlice.js

- 제목 :로그인 사람 정보 로그 남기기
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 로그인 사람 정보 로그 남기기

---

src/views/airplane/BaggageClaim.js

(확인 후 지워주세요)
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 수취대 수정

---

src/views/auth/image/ImgDialog.js
src/views/calendar/CalendarApp.js
src/views/equipment/equipmentRegist.js
src/views/facilities/facilitiesDetail.js
src/views/facilities/facilitiesRegist.js

- 제목 : feat(issue 번호): 오류 수정
<br/>
- 오류 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 오류 수정

---

src/layouts/header/Header.js
src/layouts/header/NotificationDD.js
src/views/calendar/CalendarApp.js

- 제목 : feat(issue 번호): noti 숫자
<br/>
- noti 숫자
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-14]noti 숫자

---

src/views/facilities/facilities.js
src/views/facilities/facilitiesDetail.js

- 제목 :  편의시설 수정
<br/>
-  관리자 편의시설 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-14] 편의시설 수정
